spring.application.name=socialmedia

spring.datasource.url=jdbc:postgresql://dpg-d7qc63m8bjmc73c2404g-a.oregon-postgres.render.com/socialmedia_f1wz?currentSchema=public
spring.datasource.username=socialmedia_f1wz_user
spring.datasource.password=McEVfoCacYbzhWScS2OiEl7hVlGwnnvF
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8090
spring.jpa.hibernate.ddl-auto=update