spring.application.name=MongoDB
spring.output.ansi.enabled=ALWAYS

spring.config.import=optional:file:.env[.properties]

spring.mongodb.uri=${MONGO_DB}
spring.data.mongodb.uri=${MONGO_DB}
spring.mongodb.database=studentdb
spring.data.mongodb.database=studentdb