spring.application.name=App_bean
spring.output.ansi.enabled=ALWAYS



spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=java_social_media_user
spring.datasource.password=NOLSD5jymPm12SBNdvaFft2y5IgRGHmt
spring.datasource.url=jdbc:postgresql://dpg-d7p31rjeo5us73e758f0-a.virginia-postgres.render.com/java_social_media?currentSchema=public
spring.jpa.hibernate.ddl-auto=update


spring.main.banner-mode=off

logging.level.root=warn

spring.jpa.open-in-view=false